### ISSUE TITLE
pmmp 3.9.0

### ISSUE THREAD

**Issue by note3crafter** [poggit-orphanage/EconomyS#49] opened 2019-07-14 14:18 UTC
[Server thread/CRITICAL]: Error: "Class 'pocketmine\network\mcpe\protocol\AddItemEntityPacket' not found" (EXCEPTION) in "plugins/EconomyShop(1).phar/src/onebone/economyshop/item/ItemDisplayer" at line 52

**Comment by SOF3** [comment] 2019-07-14 15:28
Duplicate of #48

**Closed by SOF3** 2019-07-14 15:28 UTC
