### ISSUE TITLE
EconomyShop Broken

### ISSUE THREAD

**Issue by note3crafter** [poggit-orphanage/EconomyS#50] opened 2019-07-15 11:22 UTC
EconomyShop is Broken i become a Internal Server Error when im teleport to the Shop can you tri to Fix It?

10:51:27] [Server thread/CRITICAL]: Error: "Class 'pocketmine\network\mcpe\protocol\AddItemEntityPacket' not found" (EXCEPTION) in "plugins/EconomyShop(1).phar/src/onebone/economyshop/item/ItemDisplayer" at line 52
[10:51:27] [Server thread/DEBUG]: #0 plugins/EconomyShop(1).phar/src/onebone/economyshop/EconomyShop(202): onebone\economyshop\item\ItemDisplayer->spawnTo(object pocketmine\Player)
[10:51:27] [Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): onebone\economyshop\EconomyShop->onPlayerTeleport(object pocketmine\event\entity\EntityTeleportEvent)
[10:51:27] [Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(object onebone\economyshop\EconomyShop, object pocketmine\event\entity\EntityTeleportEvent)
[10:51:27] [Server thread/DEBUG]: #3 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityTeleportEvent)
[10:51:27] [Server thread/DEBUG]: #4 src/pocketmine/entity/Entity(1967): pocketmine\event\Event->cal

**Comment by teracube** [comment] 2019-07-16 09:50
https://github.com/poggit-orphanage/EconomyS/issues/47

**Comment by teracube** [comment] 2019-07-16 09:51
EconomySell is broken too

**Comment by SOF3** [comment] 2019-07-16 19:26
Duplicate of #47

**Closed by SOF3** 2019-07-16 19:26 UTC
