### ISSUE TITLE
spam click (EconomyShop)

### ISSUE THREAD

**Issue by llronaldoll** [poggit-orphanage/EconomyS#30] opened 2018-08-10 10:53 UTC
when I click to buy, a spam happens and the purchase is made several times (EconomyShop)

**Comment by Awzaw** [comment] 2018-08-14 18:58
I can't reproduce this - do you have any plugins installed which might replay clicks?

**Comment by MSG100TC** [comment] 2018-12-22 15:32
Same issue

**Comment by Awzaw** [comment] 2019-03-20 22:35
Fixed in 1bd4d285709, you now have to move between purchases.

**Closed by Awzaw** 2019-03-20 22:35 UTC
